# Generated by Django 2.1.7 on 2019-03-17 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('position', 'restaurant', 'user')},
        ),
    ]
