# Generated by Django 2.1.7 on 2019-03-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190319_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('Sa', 'Saturday'), ('Su', 'Sunday'), ('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttype',
            name='restaurant',
            field=models.CharField(choices=[('Japanese', 'Japanese'), ('Italian', 'Italian'), ('Mexican', 'Mexican')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='foodtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='restaurants.RestaurantType'),
        ),
    ]
