# Generated by Django 2.1.7 on 2019-03-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20190319_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restauranttype',
            name='restaurant',
            field=models.CharField(choices=[('Japanese', 'Japanese'), ('Italian', 'Italian'), ('Mexican', 'Mexican')], max_length=20),
        ),
    ]
