# Generated by Django 2.1.7 on 2019-11-04 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={},
        ),
        migrations.AlterField(
            model_name='restaurantuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='queue',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='position',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='user',
        ),
    ]
