# Generated by Django 2.1.7 on 2019-06-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
