# Generated by Django 2.1.7 on 2019-12-12 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20191104_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['-position']},
        ),
        migrations.AddField(
            model_name='queue',
            name='guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='api.Restaurant'),
        ),
        migrations.AddField(
            model_name='queue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('restaurant', 'user'), ('position', 'restaurant')},
        ),
    ]
